-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 00:01:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema space
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema space
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `space` DEFAULT CHARACTER SET utf8 ;
USE `space` ;

-- -----------------------------------------------------
-- Table `space`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`CUSTOMER` (
  `Customer_ID` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  `CustomerName` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `MembershipPoint` INT NOT NULL DEFAULT 0,
  `CustomerGrade` VARCHAR(10) NOT NULL DEFAULT 'Iron',
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`CUS_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`CUS_ADDRESS` (
  `Address` VARCHAR(50) NOT NULL,
  `CUSTOMER_Customer_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Address`, `CUSTOMER_Customer_ID`),
  INDEX `fk_CUS_ADDRESS_CUSTOMER1_idx` (`CUSTOMER_Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CUS_ADDRESS_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_Customer_ID`)
    REFERENCES `space`.`CUSTOMER` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`CUS_COUPON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`CUS_COUPON` (
  `Coupon` VARCHAR(25) NOT NULL,
  `CUSTOMER_Customer_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Coupon`, `CUSTOMER_Customer_ID`),
  INDEX `fk_CUS_COUPON_CUSTOMER1_idx` (`CUSTOMER_Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CUS_COUPON_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_Customer_ID`)
    REFERENCES `space`.`CUSTOMER` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`PRODUCT` (
  `ProductName` VARCHAR(30) NOT NULL,
  `Brand` VARCHAR(20) NOT NULL,
  `Category` VARCHAR(20) NOT NULL,
  `Price` INT NOT NULL,
  `AcquiredDate` DATE NULL,
  PRIMARY KEY (`ProductName`),
  INDEX `Category_Index` USING BTREE (`Category`) VISIBLE,
  INDEX `Brand_Index` USING BTREE (`Brand`) VISIBLE,
  INDEX `Price_High_Index` (`Price` DESC) INVISIBLE,
  INDEX `Price_Low_Index` (`Price` ASC) INVISIBLE,
  INDEX `NewArrival_Index` USING BTREE (`AcquiredDate`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`TRANS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`TRANS` (
  `CUSTOMER_Customer_ID` VARCHAR(20) NOT NULL,
  `Payment` VARCHAR(45) NOT NULL,
  `TotalPrice` VARCHAR(45) NOT NULL,
  `DateSold` DATE NOT NULL,
  `DeliveryAddress` VARCHAR(45) NOT NULL,
  `idTRANS` INT NOT NULL AUTO_INCREMENT,
  `Cancellation` VARCHAR(5) NULL DEFAULT 'No',
  PRIMARY KEY (`idTRANS`),
  INDEX `fk_CUSTOMER_has_PRODUCT_INDV_CUSTOMER1_idx` (`CUSTOMER_Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMER_has_PRODUCT_INDV_CUSTOMER1`
    FOREIGN KEY (`CUSTOMER_Customer_ID`)
    REFERENCES `space`.`CUSTOMER` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`INFLUENCER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`INFLUENCER` (
  `AdminID` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  `NickName` VARCHAR(20) NOT NULL,
  `Height` VARCHAR(45) NULL,
  `Weight` VARCHAR(45) NULL,
  PRIMARY KEY (`AdminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`STYLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`STYLE` (
  `StyleID` INT NOT NULL AUTO_INCREMENT,
  `ADMIN_AdminID` VARCHAR(20) NOT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`StyleID`),
  INDEX `fk_STYLE_ADMIN1_idx` (`ADMIN_AdminID` ASC) VISIBLE,
  CONSTRAINT `fk_STYLE_ADMIN1`
    FOREIGN KEY (`ADMIN_AdminID`)
    REFERENCES `space`.`INFLUENCER` (`AdminID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`STYLE_has_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`STYLE_has_PRODUCT` (
  `STYLE_StyleID` INT NOT NULL,
  `PRODUCT_ProductName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`STYLE_StyleID`, `PRODUCT_ProductName`),
  INDEX `fk_STYLE_has_PRODUCT_PRODUCT1_idx` (`PRODUCT_ProductName` ASC) VISIBLE,
  INDEX `fk_STYLE_has_PRODUCT_STYLE1_idx` (`STYLE_StyleID` ASC) VISIBLE,
  CONSTRAINT `fk_STYLE_has_PRODUCT_STYLE1`
    FOREIGN KEY (`STYLE_StyleID`)
    REFERENCES `space`.`STYLE` (`StyleID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STYLE_has_PRODUCT_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ProductName`)
    REFERENCES `space`.`PRODUCT` (`ProductName`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`INVENTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`INVENTORY` (
  `idINVENTORY` INT NOT NULL AUTO_INCREMENT,
  `SIze` VARCHAR(10) NOT NULL,
  `Color` VARCHAR(15) NULL,
  `Quantity` INT NOT NULL,
  `PRODUCT_ProductName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idINVENTORY`),
  INDEX `fk_INVENTORY_PRODUCT1_idx` (`PRODUCT_ProductName` ASC) VISIBLE,
  CONSTRAINT `fk_INVENTORY_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ProductName`)
    REFERENCES `space`.`PRODUCT` (`ProductName`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `space`.`TRANS_has_INVENTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `space`.`TRANS_has_INVENTORY` (
  `TRANS_idTRANS` INT NOT NULL,
  `INVENTORY_idINVENTORY` INT NOT NULL,
  `Sellprice` VARCHAR(45) NOT NULL,
  `Review` TEXT NULL,
  `Quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`TRANS_idTRANS`, `INVENTORY_idINVENTORY`),
  INDEX `fk_TRANS_has_INVENTORY_INVENTORY1_idx` (`INVENTORY_idINVENTORY` ASC) VISIBLE,
  INDEX `fk_TRANS_has_INVENTORY_TRANS1_idx` (`TRANS_idTRANS` ASC) VISIBLE,
  CONSTRAINT `fk_TRANS_has_INVENTORY_TRANS1`
    FOREIGN KEY (`TRANS_idTRANS`)
    REFERENCES `space`.`TRANS` (`idTRANS`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANS_has_INVENTORY_INVENTORY1`
    FOREIGN KEY (`INVENTORY_idINVENTORY`)
    REFERENCES `space`.`INVENTORY` (`idINVENTORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
